name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 2.7]
        node-version: [8, 10, 12]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          version: ${{ matrix.python-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node-version }}
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install poetry
        uses: dschep/install-poetry-action@v1.1
        with:
          preview: false

      - name: Install serverless
        run: npm install -g serverless

      - name: Install deps
        run: npm install

      - name: Lint
        run: npm run ci:lint

      - name: Test
        run: |
          PATH=$HOME/.poetry/bin:$PATH \
          LC_ALL=C.UTF-8 \
          LANG=C.UTF-8 \
          npm run test
        env:
          RUNTIME: python${{ matrix.python-version }}
